### ISSUE TITLE
Pagination is displayed even if total number of pages is one.

### ISSUE THREAD

**Issue by sushan05** [appcarvers/ngx-unite-list#1]
The pagination should only be displayed if the total pages are more than one.

**Comment by vilbergs** [comment]
I'd love to have a go at this one

**Comment by sushan05** [comment]
Thanks @vilbergs , we really appreciate your contribution and looking forward for more such contributions :)

Meanwhile, if you are interested, we found one more issue  - https://github.com/appcarvers/ngx-unite-list/issues/4

**Comment by sushan05** [comment]
#closing this issue
